# Generated by Django 3.1.1 on 2020-12-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20201230_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='map1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='map2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='move',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='port',
            field=models.IntegerField(default=8080),
        ),
        migrations.AlterField(
            model_name='room',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
