# Generated by Django 3.1.1 on 2020-12-29 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Room', '0003_auto_20201230_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='auth.user'),
        ),
    ]
