# Generated by Django 3.1.1 on 2021-01-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_auto_20201230_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='history',
        ),
    ]
