# Generated by Django 3.1.1 on 2021-01-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_remove_room_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='move',
            new_name='move1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='map1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='map2',
        ),
        migrations.AddField(
            model_name='room',
            name='result1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='result2',
            field=models.IntegerField(default=0),
        ),
    ]
