# Generated by Django 3.1.1 on 2021-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_auto_20210104_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='move2',
            field=models.IntegerField(default=-1),
        ),
    ]
