# Generated by Django 3.1.1 on 2021-01-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_room_move2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='result1',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='room',
            name='result2',
        ),
    ]
