# Generated by Django 3.1.1 on 2021-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_auto_20210106_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
